
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres'%>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: store_development
  url: <%= ENV['DATABASE_URL'] %>
  

test:
  <<: *default
  database: store_test
  url: <%= ENV['DATABASE_URL'] %>
  


production:
  <<: *default
  database: store_production
  username: store
  url: <%= ENV['DATABASE_URL'] %>
  